export const CHAIN_REGISTRY_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "CAIP2HashAlreadyRegistered", type: "error" },
  { inputs: [], name: "ChainAlreadyRegistered", type: "error" },
  { inputs: [], name: "ChainNameAlreadyRegistered", type: "error" },
  { inputs: [], name: "ChainNameEmpty", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "StringsInvalidChar", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "chainId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "chainName",
        type: "string",
      },
    ],
    name: "ChainRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "caip2HashToChainId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "caip2HashUsed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "chainData",
    outputs: [
      { internalType: "string", name: "chainName", type: "string" },
      { internalType: "uint256", name: "settlementChainId", type: "uint256" },
      { internalType: "string", name: "version", type: "string" },
      { internalType: "address", name: "rollupContract", type: "address" },
      { internalType: "string", name: "chainNamespace", type: "string" },
      { internalType: "string", name: "chainReference", type: "string" },
      { internalType: "uint256", name: "coinType", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "namespace", type: "string" },
      { internalType: "string", name: "chainReference", type: "string" },
    ],
    name: "chainDataFromCaip2",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      {
        components: [
          { internalType: "string", name: "chainName", type: "string" },
          {
            internalType: "uint256",
            name: "settlementChainId",
            type: "uint256",
          },
          { internalType: "string", name: "version", type: "string" },
          { internalType: "address", name: "rollupContract", type: "address" },
          { internalType: "string", name: "chainNamespace", type: "string" },
          { internalType: "string", name: "chainReference", type: "string" },
          { internalType: "uint256", name: "coinType", type: "uint256" },
        ],
        internalType: "struct ChainData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "ensCoinType", type: "uint256" }],
    name: "chainDataFromEnsCoinType",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      {
        components: [
          { internalType: "string", name: "chainName", type: "string" },
          {
            internalType: "uint256",
            name: "settlementChainId",
            type: "uint256",
          },
          { internalType: "string", name: "version", type: "string" },
          { internalType: "address", name: "rollupContract", type: "address" },
          { internalType: "string", name: "chainNamespace", type: "string" },
          { internalType: "string", name: "chainReference", type: "string" },
          { internalType: "uint256", name: "coinType", type: "uint256" },
        ],
        internalType: "struct ChainData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "chainId", type: "bytes32" }],
    name: "chainDataFromId",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      {
        components: [
          { internalType: "string", name: "chainName", type: "string" },
          {
            internalType: "uint256",
            name: "settlementChainId",
            type: "uint256",
          },
          { internalType: "string", name: "version", type: "string" },
          { internalType: "address", name: "rollupContract", type: "address" },
          { internalType: "string", name: "chainNamespace", type: "string" },
          { internalType: "string", name: "chainReference", type: "string" },
          { internalType: "uint256", name: "coinType", type: "uint256" },
        ],
        internalType: "struct ChainData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "chainNameUsed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "chainName", type: "string" },
          {
            internalType: "uint256",
            name: "settlementChainId",
            type: "uint256",
          },
          { internalType: "string", name: "version", type: "string" },
          { internalType: "address", name: "rollupContract", type: "address" },
          { internalType: "string", name: "chainNamespace", type: "string" },
          { internalType: "string", name: "chainReference", type: "string" },
          { internalType: "uint256", name: "coinType", type: "uint256" },
        ],
        internalType: "struct ChainData",
        name: "_chainData",
        type: "tuple",
      },
    ],
    name: "demoRegister",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "ensCoinTypeToChainId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "chainName", type: "string" },
          {
            internalType: "uint256",
            name: "settlementChainId",
            type: "uint256",
          },
          { internalType: "string", name: "version", type: "string" },
          { internalType: "address", name: "rollupContract", type: "address" },
          { internalType: "string", name: "chainNamespace", type: "string" },
          { internalType: "string", name: "chainReference", type: "string" },
          { internalType: "uint256", name: "coinType", type: "uint256" },
        ],
        internalType: "struct ChainData",
        name: "_chainData",
        type: "tuple",
      },
    ],
    name: "register",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const CHAIN_RESOLVER_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_chainRegistry", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ChainNameEmpty", type: "error" },
  { inputs: [], name: "LabelAlreadyAssigned", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "uint256", name: "length", type: "uint256" },
    ],
    name: "StringsInsufficientHexLength",
    type: "error",
  },
  { inputs: [], name: "UnsupportedFunction", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "node", type: "bytes32" },
      { indexed: true, internalType: "string", name: "label", type: "string" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "chainId",
        type: "bytes32",
      },
    ],
    name: "NodeAssigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "CHAIN_REGISTRY",
    outputs: [
      { internalType: "contract IChainRegistry", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "label", type: "string" },
      { internalType: "bytes32", name: "chainId", type: "bytes32" },
    ],
    name: "assign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "chainName", type: "string" }],
    name: "computeNode",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "label", type: "string" },
      { internalType: "bytes32", name: "chainId", type: "bytes32" },
    ],
    name: "demoAssign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "nodeToChainId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "name", type: "bytes" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "resolve",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const CAIP2_LIB_ABI = [
  {
    inputs: [
      { internalType: "string", name: "namespace", type: "string" },
      { internalType: "string", name: "chainReference", type: "string" },
    ],
    name: "computeCaip2Hash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
] as const;
